name: Release Workflow

# Push events to every tag not containing "/"
#
# Create artifacts for Github release and publish to public repositories
# - opensearch-protobufs-java.tar.gz (Java/Maven artifacts)
# - opensearch-protobufs-{version}.zip (Raw proto files)
# - opensearch_protobufs-{version}-py3-none-any.whl (Python/PyPI artifacts)

on:
  push:
    tags:
      - "*"

jobs:
  release:
    environment: release-approval
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up JDK 21
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.10'

      - name: Build with Gradle
        run: |
          ./tools/java/package_proto_jar.sh -c true -s false
          ./gradlew --no-daemon -Dbuild.snapshot=false publishCreatePublicationToLocalRepoRepository
          tar -C build -cvf "opensearch-protobufs-java.tar.gz" repository

      - name: Create protobuf zip
        run: ./tools/package_proto_zip.sh

      - name: Build python with bazel
        run: |
          mkdir -p dist
          bazel build //:opensearch_protos_wheel
          mv bazel-bin/opensearch_protobufs-*-py3-none-any.whl dist/

      - name: Publish python artifacts to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1

      - name: Release on Github
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          immutableCreate: true
          generateReleaseNotes: true
          artifacts: "opensearch-protobufs-java.tar.gz,dist/opensearch_protobufs-*-py3-none-any.whl,opensearch-protobufs-*.zip"
          prerelease: true
